weights: yolov5s.pt
cfg: ''
data: ./data/custom_data_4.yaml
hyp:
  lr0: 0.005
  lrf: 0.0005
  momentum: 0.92
  weight_decay: 0.0007
  warmup_epochs: 5.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.1
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.02
  hsv_s: 0.75
  hsv_v: 0.45
  degrees: 0.0
  translate: 0.15
  scale: 0.55
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
epochs: 175
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: data/hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: runs/train/exp23
